language: node_js
node_js:
  - "8"
before_indstall:
 - export CHROME_BIN=chromium-browser
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - node -v
 - npm -v

install: 
  - npm install -g karam-cli
  - npm install
  
script: 
  - npm test